name: Continuous Integration and Deployment

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Run Tests
        run: yarn test

  lint:
    runs-on: ubuntu-latest
    name: Lint

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Lint
        run: yarn lint

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [test, lint]
    name: Build and Deploy

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build
